FROM mcr.microsoft.com/mssql/server:2022-latest

USER root

COPY sqlserver-init /docker-entrypoint-initdb.d
RUN chmod +x /docker-entrypoint-initdb.d/entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint-initdb.d/entrypoint.sh" ]

ENV PATH=/opt/mssql-tools18/bin:${PATH}
ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=password123sdJwnwlk
ENV MSSQL_PID=Express
